// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeting/greetingpb/greeting.proto

package greetingpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetingMessage struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingMessage) Reset()         { *m = GreetingMessage{} }
func (m *GreetingMessage) String() string { return proto.CompactTextString(m) }
func (*GreetingMessage) ProtoMessage()    {}
func (*GreetingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_edee392dc93c6fb4, []int{0}
}

func (m *GreetingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingMessage.Unmarshal(m, b)
}
func (m *GreetingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingMessage.Marshal(b, m, deterministic)
}
func (m *GreetingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingMessage.Merge(m, src)
}
func (m *GreetingMessage) XXX_Size() int {
	return xxx_messageInfo_GreetingMessage.Size(m)
}
func (m *GreetingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingMessage proto.InternalMessageInfo

func (m *GreetingMessage) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type GreetingRequest struct {
	Greeting             *GreetingMessage `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edee392dc93c6fb4, []int{1}
}

func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (m *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(m, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

func (m *GreetingRequest) GetGreeting() *GreetingMessage {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetingResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edee392dc93c6fb4, []int{2}
}

func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (m *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(m, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetingMessage)(nil), "example.greeting.GreetingMessage")
	proto.RegisterType((*GreetingRequest)(nil), "example.greeting.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "example.greeting.GreetingResponse")
}

func init() { proto.RegisterFile("greeting/greetingpb/greeting.proto", fileDescriptor_edee392dc93c6fb4) }

var fileDescriptor_edee392dc93c6fb4 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2f, 0x4a, 0x4d,
	0x2d, 0xc9, 0xcc, 0x4b, 0xd7, 0x87, 0x31, 0x0a, 0x92, 0xe0, 0x4c, 0xbd, 0x82, 0xa2, 0xfc, 0x92,
	0x7c, 0x21, 0x81, 0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0x3d, 0x98, 0xb8, 0x92, 0x01, 0x17,
	0xbf, 0x3b, 0x94, 0xed, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x24, 0xcb, 0xc5, 0x95, 0x96,
	0x59, 0x54, 0x5c, 0x12, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4,
	0x09, 0x16, 0xf1, 0x4b, 0xcc, 0x4d, 0x55, 0x0a, 0x40, 0xe8, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0xb2, 0xe5, 0xe2, 0x80, 0x19, 0x08, 0x56, 0xcf, 0x6d, 0xa4, 0xa8, 0x87, 0x6e, 0x93,
	0x1e, 0x9a, 0x35, 0x41, 0x70, 0x2d, 0x4a, 0x5a, 0x5c, 0x02, 0x08, 0x13, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0x0e, 0x80, 0xf2,
	0x8c, 0x04, 0x11, 0xb6, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x3a, 0xf1, 0x44, 0x71, 0x21,
	0x7c, 0x9c, 0xc4, 0x06, 0xf6, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xee, 0x3e, 0x8e, 0xeb,
	0x0f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetingServiceClient interface {
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

// GreetingServiceServer is the server API for GreetingService service.
type GreetingServiceServer interface {
}

// UnimplementedGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.greeting.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "greeting/greetingpb/greeting.proto",
}
